[tool.poetry]
name = "thefractalbot-web"
version = "0.1.0"
description = ""
authors = ["ddorn <diego.dorn@free.fr>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
brocoli = { git = "https://gitlab.com/ddorn/brocoli" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
